stages:
  - test
  - deploy
  
image: elixir:1.9

test:
  stage: 
    - test

  services:
    - postgres:11
    
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres # must match config/test.exs
    POSTGRES_PASSWORD: postgres # must match config/test.exs
    MIX_ENV: "test"

  before_script:
    - apt-get update -y && apt-get install wkhtmltopdf xvfb -y
    - mix local.rebar --force
    - mix local.hex --force

  script:
    - mix deps.get --only test
    - mix ecto.reset
    - mix test

  only:
    - master
    - merge_requests
    - branches

deploy:
  stage: deploy
  script:
    - git remote add take_the_risk https://ivan:xpOWsn0Q!@gitlab.taketherisk.mx/take_the_risk/take_the_risk.git
    - git push -f take_the_risk HEAD:refs/heads/master
  when: manual
  only:
    - branches    

