image: elixir:1.9

services:
  - postgres:11

variables:
  POSTGRES_DB: remote_jobs_dev
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: "postgres"
  MIX_ENV: "test"


before_script:
  - apt-get update -y && apt-get install wkhtmltopdf xvfb -y && apt-get install postgresql-client
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  - mix ecto.setup

mix_tests:
  script:
    - mix test