stages:
  - test
  
image: elixir:1.9

test:
   stage: test
   
   services:
     - postgres:11

   variables:
     POSTGRES_HOST: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     MIX_ENV: "test"

   before_script:
     - apt-get update -y && apt-get install wkhtmltopdf xvfb -y
     - mix local.rebar --force
     - mix local.hex --force

   script:
     - mix deps.get --only test
     - mix ecto.reset
     - mix test

   only:
     - master
     - merge_requests
     - branches